"apiVersion": "kustomize.config.k8s.io/v1beta1"
"kind": "Kustomization"
"patches":
- "path": "kured.yaml"
"resources":
- "kured-base.yaml"
- "hcloud-ccm-helm.yaml"
- "hcloud-csi.yaml"
- "flannel-rbac.yaml"
