# Inputs for the infrastructure layer.
#
# Nothing here has a default that would silently provision something. Where a
# default exists it is either a shape (a port, a CIDR, a count) or a value that
# is wrong to guess, in which case there is no default and tofu will stop.

# ---------------------------------------------------------------------------
# Credentials
# ---------------------------------------------------------------------------

variable "hcloud_token" {
  description = "Hetzner Cloud API token, Read & Write. Project > Security > API Tokens."
  type        = string
  sensitive   = true
}

variable "state_passphrase" {
  description = <<-EOT
    Passphrase for OpenTofu's client-side state and plan encryption.

    Read during `tofu init`, before state exists, so it must come from the
    environment: export TF_VAR_state_passphrase='…'. Losing it means losing the
    ability to read your own state — treat it like the age key.
  EOT
  type        = string
  sensitive   = true

  validation {
    # OpenTofu's own floor for a PBKDF2 passphrase. Checked here so the failure
    # is a named validation error rather than an init-time key derivation error
    # several layers down.
    condition     = length(var.state_passphrase) >= 16
    error_message = "state_passphrase must be at least 16 characters."
  }
}

variable "ssh_public_key" {
  description = "Contents of the SSH public key used to reach the nodes. The module writes it to every node's root authorized_keys."
  type        = string
}

variable "ssh_private_key" {
  description = "Contents of the matching SSH private key. Used by the provisioners during bootstrap; set to null if your key is only in an agent."
  type        = string
  sensitive   = true
  default     = null
}

# ---------------------------------------------------------------------------
# Object storage
#
# Two buckets, created by scripts/bootstrap-buckets.sh before the first init.
# They are separate buckets and not prefixes because they want OPPOSITE
# lifecycle policies: state keeps versions indefinitely, snapshots expire. In
# one bucket, the day somebody adds an expiry rule to stop paying for old
# snapshots they are one prefix pattern away from expiring state history — and
# the thing destroyed is the recovery path, discovered only during a recovery.
# ---------------------------------------------------------------------------

variable "object_storage_endpoint_host" {
  description = <<-EOT
    Object storage endpoint as a BARE HOST, no scheme: <location>.your-objectstorage.com.

    k3s wants a host here; the s3 backend in versions.tf wants a URL and cannot
    read variables at all. That duplication is unavoidable and is flagged in
    both places: if you change one, change the other.
  EOT
  type        = string
  default     = "fsn1.your-objectstorage.com"

  validation {
    condition     = !can(regex("^https?://", var.object_storage_endpoint_host))
    error_message = "object_storage_endpoint_host must be a bare host without a scheme — k3s rejects a URL here."
  }
}

variable "object_storage_region" {
  description = "Storage location code, e.g. fsn1. Not an AWS region; the backend disables region validation for exactly this reason."
  type        = string
  default     = "fsn1"
}

variable "object_storage_access_key" {
  description = "Object storage access key. Generated by hand in the provider console — the provider CLI has no object-storage commands, so this step cannot be automated."
  type        = string
  sensitive   = true
}

variable "object_storage_secret_key" {
  description = "Object storage secret key."
  type        = string
  sensitive   = true
}

variable "etcd_snapshot_bucket" {
  description = "Bucket for etcd snapshots. MUST NOT be the state bucket — see the comment above; this is the bucket carrying an expiry rule."
  type        = string
  default     = "example-etcd-snapshots"
}

variable "etcd_snapshot_schedule_cron" {
  description = "Cron schedule for etcd snapshots, in k3s's own scheduler."
  type        = string
  default     = "0 */6 * * *"
}

variable "etcd_snapshot_retention" {
  description = <<-EOT
    How many snapshots k3s itself keeps.

    This is the near-side of a two-sided retention story: k3s prunes what it
    knows about, and the bucket lifecycle rule set by the bootstrap script is
    the backstop for everything k3s forgets — snapshots from a control plane
    that was replaced, or from a cluster that no longer exists. Keep the bucket
    rule strictly longer than this, or the backstop deletes live snapshots.
  EOT
  type        = number
  default     = 20
}

# ---------------------------------------------------------------------------
# Cluster shape
# ---------------------------------------------------------------------------

variable "cluster_name" {
  description = "Cluster name. Prefixes node names and therefore the autoscaler node-group names the priority expander matches on."
  type        = string
  default     = "platform"

  validation {
    condition     = can(regex("^[a-z0-9-]+$", var.cluster_name))
    error_message = "cluster_name must be lowercase alphanumeric characters and dashes."
  }
}

variable "network_region" {
  description = "Network region. All locations used below must sit inside it."
  type        = string
  default     = "eu-central"
}

variable "control_plane_location" {
  description = "Location for the control plane nodes."
  type        = string
  default     = "fsn1"
}

variable "control_plane_server_type" {
  description = <<-EOT
    Instance type for the three control plane nodes. x86 shared vCPU.

    CHECK THAT THIS TYPE IS CURRENTLY AVAILABLE in control_plane_location, not
    merely supported. Those are different fields in the provider API and a
    supported-but-unavailable type plans and applies cleanly.
  EOT
  type        = string
  # Was cx33 until 2026-08-04, when the entire shared-Intel (cx) line went
  # unavailable in every fsn1 datacentre. cpx22 is 2 vCPU / 4 GB at EUR 24.36
  # gross -- adequate for a control plane, which schedules rather than works.
  default     = "cpx22"
}

variable "agent_location" {
  description = "Location for the fixed agent nodepool."
  type        = string
  default     = "fsn1"
}

variable "agent_server_type" {
  description = "Instance type for the fixed agent nodepool. CHECK CURRENT AVAILABILITY in agent_location, not merely support."
  type        = string
  # Was cx43. See control_plane_server_type: the cx line is gone from fsn1.
  # cpx32 is 4 vCPU / 8 GB at EUR 44.36 gross.
  default     = "cpx32"
}

# ---------------------------------------------------------------------------
# TRONGATE-CLOUD: profile switches. Defaults reproduce the kit; the values for
# the single-node trongate.cloud cluster are in trongate-cloud.auto.tfvars.
# ---------------------------------------------------------------------------

variable "enabled_architectures" {
  description = "CPU architectures the module may provision: [\"x86\"] (the kit's default) or [\"arm\"] for CAX types. Every nodepool must match."
  type        = list(string)
  default     = ["x86"]
}

variable "control_plane_count" {
  description = "Control plane nodes: 1 (non-HA) or 3. Never 2, and never shrink a running cluster -- see main.tf."
  type        = number
  default     = 3

  validation {
    condition     = contains([1, 3, 5], var.control_plane_count)
    error_message = "control_plane_count must be 1, 3 or 5 (an odd etcd quorum)."
  }
}

variable "allow_scheduling_on_control_plane" {
  description = "Let workloads run on control plane nodes. Required when agent_count is 0."
  type        = bool
  default     = false
}

variable "enable_klipper_lb" {
  description = "Serve LoadBalancer Services from the nodes' own IPs (k3s servicelb) instead of a Hetzner load balancer."
  type        = bool
  default     = false
}

variable "automatically_upgrade_os" {
  description = "Unattended OS updates with kured reboots. kube-hetzner advises false for single-node clusters."
  type        = bool
  default     = true
}

variable "registries_config" {
  description = <<-EOT
    k3s registries.yaml contents, written to every node. Carries the pull-only
    credential for the platform registry, so supply it from the environment
    (TF_VAR_registries_config) or the gitignored terraform.tfvars, never from a
    committed file. See TRONGATE-CLOUD.md for the shape. The module pushes a
    changed value to existing nodes over SSH on the next apply.
  EOT
  type        = string
  sensitive   = true
  default     = " "
}

variable "agent_count" {
  description = "Fixed agent nodes. These carry the workloads the autoscaler is not allowed to take away — ingress, storage, anything with a disruption budget."
  type        = number
  default     = 2
}

# ---------------------------------------------------------------------------
# Autoscaler
# ---------------------------------------------------------------------------

variable "autoscaler_location" {
  description = "Location for the primary (cost-optimised) autoscaler pool."
  type        = string
  default     = "fsn1"
}

variable "autoscaler_server_type" {
  description = <<-EOT
    Instance type for the primary autoscaler pool: the cost-optimised x86 line.

    CHECK CURRENT AVAILABILITY in autoscaler_location, not merely support. This
    is the pool where the distinction bites hardest — an unavailable type here
    fails at the exact moment you needed capacity, and every layer of tooling
    reports success right up until the provider refuses.

    Recorded 2026-08-03: the cost-optimised line was present in ONE location
    while the pricier lines were present in all of them.

    Recorded 2026-08-04, ONE DAY LATER: that line was gone from fsn1 entirely --
    not the type, the whole cx family, across all three datacentres. The default
    here moved cx43 -> cpx32 as a result. Both of these are dated observations,
    and the speed with which the first became wrong is the entire argument for
    running scripts/checks/check-pool-availability.py before every apply rather
    than trusting any value committed to this file, including this one.
  EOT
  type        = string
  default     = "cpx32"
}

variable "autoscaler_max_nodes" {
  description = "Ceiling for the primary autoscaler pool. min_nodes is 0 — an idle pool costs nothing."
  type        = number
  default     = 5
}

variable "autoscaler_fallback_location" {
  description = "Location for the commented-out cross-location fallback pool in main.tf. Must differ from autoscaler_location or the pool is not insurance against anything."
  type        = string
  default     = "nbg1"
}

variable "autoscaler_fallback_server_type" {
  description = <<-EOT
    Instance type for the commented-out fallback pool: the line stocked in every
    location, at roughly four times the price per core.

    Must be the SAME SHAPE as the primary, or the fallback quietly changes the
    capacity of a scale-out rather than merely its cost. Verified against the
    provider's pricing API on 2026-08-03, net of VAT, hel1:

      cx43   8 vCPU / 16 GB   EUR 15.99   hel1 ONLY        <- primary
      cpx42  8 vCPU / 16 GB   EUR 69.49   fsn1 hel1 nbg1   <- this default, 4.3x
      ccx23  4 vCPU / 16 GB   EUR 85.99   fsn1 hel1 nbg1   <- NOT like-for-like

    That last row is why this carries a stated shape rather than a free choice:
    ccx23 reads as a reasonable fallback and is half the cores for more money.
    Compare vCPU and memory, not price alone.

    UNPROVEN UNTIL PROVISIONED. A fallback that has never once come up is not
    insurance — it is a second way to be unavailable, and its presence stops
    anyone from looking. Check availability here on the same schedule as the
    primary, and re-check the figures above: they are a dated observation, not
    a property.
  EOT
  type        = string
  default     = "cpx42"
}
