apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:qMJWKVI=,iv:DPdsVYtKg86yFamLkOEe68zmddCvfaUYu9I8E0W5+ZE=,tag:VOin16MLwTFcdmo4FoBrog==,type:str]
    admin-password: ENC[AES256_GCM,data:5Z390TCR4jksXGbvJraygG8/6A0P8R1wcPT/71/8vqE=,iv:uXEM00W9nGAmGXOQU6aMgudt4Thefd2aX3IxLcdkdt4=,tag:vSVoX3wVaa30CfTlmD8kJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSW1XSUQrUWVBMENUdlJ0
            SGVkTkRpQ1VtUFZ5TWxuMTFlVzNkWjBwS0ZBCmhCZ3ZKY1lWazNYUG5KaEJRRU5T
            QnVWelJ1dGZxSE5HZHMrbXY3L2EvQVUKLS0tIDBKNHNPOXQycUhjNS9QVlNuQjk0
            S3lKUGVkbjM0eTFFRlNLeGl0aFBHZk0Ka9Nf+JH7FYOEvi0irnjUV4/WXQUvYpOT
            03lWtMD9H4x6Uet0zlNSX9+53IvNM1dfPSoLaQeBfHakKOF6/liWRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eyp26flc48tlgy32tmawjjvut92skkts9y3qycwtqpgqyunmu4zqjchqz6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T19:32:47Z"
    mac: ENC[AES256_GCM,data:9f68TNRCZcN2W7ZgRFnMmbMVqXUPxAXIy/5Up3pU4nEGVPTsTxrkihZ+RvuD5uhW292ZAHx5xVx6ty/KnA3scsIF8sjMVvzTpR0IHVGed1rifRbKv+96E5pPpsNDxX0i3UGCJOksz4EKMt0UIPjZtufu7cEHF79GktS6FaJ8j5A=,iv:vNmRxM54wCCIo2ZqL7GLsbkqBUBhHUZqgdB0D3RZDlQ=,tag:+26flcyI6Qe67PAib1mGLA==,type:str]
    version: 3.13.3
