apiVersion: v1
kind: Secret
metadata:
    name: registry-pull
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:Hw1rvZX8y6mMO9OEOUq9UmikJ7iI+bWfaX7MXygCR2tXeWL53pp7eQkorFeh304y3sqaduuMdb1Gwo5QSiMzB2SNWqkfjO4oozt4zRoTkZZV2ADU9mg01hJd4t0zwBZanyuWBkBBeMlU+P6Ksbg49+pILE+RYL2AxWaroVF5h78Py2FjiTZ3/TgbGHfd6WcQ,iv:H2FfFs4qLQ5zaTzXiTFo+n3DMSvFLw/3BD7+dCrARFM=,tag:+yNpQhECvOTLxfQZPHRvFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRk9rUE1UQ0RLSFZXQzAy
            Y0Z1OWttSk4xOHVsVGxuOGpiTWNEMng1andjCi8zajR0bEx6QWY2RlNkajZMbG5Q
            RXY1RHNVN2RJS3F0Rk40bFo3V2NVKzgKLS0tIHRNVDFqKzlmN0VDbDkrUldMNmpn
            QmRzUE5QMFJ5Y1RZQStDbVJSazZvbHcK+iwod6eva+axdH33Sgx4T7gmPIzE8tzb
            dye5DRZ8Z8sDh4SGoCN3kY29dq0tK4aNfxsvjjqS4LwhdjcM/6rtmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eyp26flc48tlgy32tmawjjvut92skkts9y3qycwtqpgqyunmu4zqjchqz6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T16:48:09Z"
    mac: ENC[AES256_GCM,data:gLRxhBsH7jTdYnXpHPTB7J1GbS9ByVFjSfCQ4ynAe+BvgXSyopJJaiyfhr8g1+4JUDRN3sO2MBMgKb8xTjXuDN0Zws8z6d7y2bNWF5Q6VenVqBxztvAKvEfM0ab4CxcFL0FJ+gxRXkNQkH2JyX5+49oaRcdqB5McvRxUm1u7vwM=,iv:N4W6Dit5QmO+ki2v9GQKcmyaZ4WuY213uutdMl5Lf+A=,tag:RMf3Zg0PwqO4OVon90pjFQ==,type:str]
    version: 3.13.3
