apiVersion: v1
kind: Secret
metadata:
    name: registry-config
    namespace: registry
type: Opaque
stringData:
    http-secret: ENC[AES256_GCM,data:Tok/jgpXG8PWsjsFuvHD+t7L/rAHduetfvIFbEOiLWOm0/9kTtIFg+9nsPL0PKOYzVAq2BXBulYscJnV//AsyQ==,iv:4VBRYCu1uxORwiP15xyxjmicAEGyYy4K5NO4wPfBv+U=,tag:Ql4Hpn03sn7g4GzJWTkZoQ==,type:str]
    htpasswd: ENC[AES256_GCM,data:jMhzjFbfUJdKU4+YBZAMEuyf0FHEyJy5Ga+8rQnlZ4WjcqbmpeEQqiTie1W+4Xq4d3AQYmIousNYAGjD18d8rZau0EAepICXD7R0XvPz5Zu7Y9bWU2WKODjAlM/wdLBwy0P7gqj/seB55M+8G5UdibJXBdqUVVHu9JhE79c88KQyHCMH,iv:DwWs3ilaMlv4qIudzsE9J40ggdAkScrFt1Qiy7M+jCA=,tag:az1rVWjtEYh8t4VjlpxCTg==,type:str]
    bucket: ENC[AES256_GCM,data:BzhzLps5Pir17nh5R0Mqmc/X/oCMxZoK4mQJCQ==,iv:jaqE0TlRH+T5Zw6JOFoeHY4sGM9dNeFP/X97ZzRX19Q=,tag:suCInKH8fmG2gs08klvMGQ==,type:str]
    access-key: ENC[AES256_GCM,data:yy8qw6os/OV5EEUeGjYWxm/dVXw=,iv:YY6e9nXaI3AAK+omfljRnYBJQY1die4HyYYEF5wKHUM=,tag:8ygempfalVuStOySBJ7a4Q==,type:str]
    secret-key: ENC[AES256_GCM,data:sBi6KiPD/94S7ltVn42kBSl2O8UCNN+9IaSzOB19Vecbx/O+Dk/BTQ==,iv:Bh1mF3qO0u4Vr8wb3IZ7mmELsIWKkuqkpxNvj6S5cw0=,tag:llgg+K6WrYsVWv/ZxBfemg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MGl1U0JOWmEvWjhhKzNy
            eENRNndSS0xqRGp0NjJ2UlVuSkF1cmhKNUEwClFhU2huM28rTTBjMU4rSno4R25U
            Q1pJVDNWMGRjbk9YQnM2RzFybEJyTFkKLS0tIDlCcjJ1Q09vQ2ljSnVsdTBWalFv
            TDd3Q2JrdkYwbDVobEc3bWJkWm1mN3cKlMn8Z+7/0UeQ7gXk7Iz9spNwZXqlPGSk
            L7QANLWxX+vHWh7bBVpnHjHAeqlDOXtYWEj21BPI5sHuGDbJv2hW9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eyp26flc48tlgy32tmawjjvut92skkts9y3qycwtqpgqyunmu4zqjchqz6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T08:45:59Z"
    mac: ENC[AES256_GCM,data:dbgzpfdonmIIC1koePVChmLZITvi4kfUF9PS4roxA5YZqGWrLK441S8EvMig/5QMC3C7nDnXcQFE9JDeSI+1zcVN7whxMPUCf8yZh3QVr9cLPAMuuKpXUYMo1qAFjNVDYIoe/T15EdnCTPCAndYhY0NDbh2RGiy842Ovm37gCqQ=,iv:ylxDsFFwKV/sbt8xnLXV7yFEp19PZnOMIBoNBfsw1qo=,tag:o8aPK5b+b2IBAkyG1QFh+A==,type:str]
    version: 3.13.3
