apiVersion: v1
kind: Secret
metadata:
    name: registry-config
    namespace: registry
type: Opaque
stringData:
    http-secret: ENC[AES256_GCM,data:VvGA3mC+KneUTVfqX9gKaSeqoaadwr7YDJudQp5CIZGu17E+QI+YrhET9Y0J0JHh52O7eDgLULqdD0Wv1iTMjQ==,iv:YNbloumDBSgCyAtczNbT29NZWmmn7NEIuj6uncbNEQA=,tag:ft8wtmRaUTDsom3BhyHP4w==,type:str]
    htpasswd: ENC[AES256_GCM,data:L1IDMiwsTQ4SxUeOFBr3H9ReGUYjR26CFf6E39A9hj9DC7RljxxuwUHhPsmO29+8hlLgf8BTVi1JOhFbJQ9dgblQLjFxnVBdMSl7LrchfyQfHRAPKk2VDkcG/D6wQU00y4FbOmh+O6FhLsUkDj4LGqa1QieUM7UKwXblck5tgMk5XJld,iv:66HYs28SLmVXS6mqsB6MAOX7lJephjeYrcVyiyx3ViA=,tag:wvbV6iTVzD+r0JPkXFB2Bg==,type:str]
    bucket: ENC[AES256_GCM,data:Vnm9/tLBzjFa8urQ2Vsco18NwUhUNPY=,iv:f5hC2hL/eBpFqvP9CZzo5/r7HxGZECeElkdlSgkT7ko=,tag:QanBlAP2inq3QSYjZOKKuw==,type:str]
    access-key: ENC[AES256_GCM,data:fcdcxVN9vY1vGgIhdn07PsozPc8=,iv:vabPu52lPkunzBN0ed7gxo/SkhLGK6UrUe2hYNZKqHA=,tag:ZmHGID0p0+XLyuBh11XA4Q==,type:str]
    secret-key: ENC[AES256_GCM,data:Io7rC93IqlRF25ndnuCPrlF3D554CtFnmJFbA5r9Z5EA38zwc9z3rA==,iv:lcKv8kdLITQxvTwqWPohXOE0bqT70b/8vVMnUzzzW5U=,tag:Yp+yq+SntXDH8srW9fZFhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQXFEY01RNFl1UDRCKytw
            TXI2YnlSb1NyajlRb0xTVWFnZlB4RXFab1hjCmU4dzJQWDVmWkNNckFGN3diNURp
            RjhmcWZwazVCNGNRK0ZrQU12Q1oxMlEKLS0tIDdNMGIxWjAzNHM0L1RPbzR1SnRj
            bDUxYmY3eUZmRGFndUludExrRmNHbk0K0yG9IJDkl7anPRh5R2Df9vj5LDLEc6wN
            Af97yBIi0+9RwM6q7qcKtmw3Gs8aTMuvdtTYByc07TQDZfzCld/qNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eyp26flc48tlgy32tmawjjvut92skkts9y3qycwtqpgqyunmu4zqjchqz6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T20:18:22Z"
    mac: ENC[AES256_GCM,data:46/XKTCLDnSA/e6HfrEb0m5YWPdKEYpc2pevRZ+J425wOXAWG0g8eSukQ2y/54GfJyjF3eIcqoCv3VfhjjlWYmajFIK/zhQZZtx+Nojfqxml5bhh5IQMzIe+ioQ3YkScMfr40uJFhUqOvphXUyRIII53/G2EwObgjg99tO+N124=,iv:jlhjTRpTllv6jLx6FDbGqj1mcQ38bf34Mq43Xv3rWmM=,tag:zS5/DSgXubmOH3tyhp4VJg==,type:str]
    version: 3.13.3
