apiVersion: v1
kind: Secret
metadata:
    name: valkey-acl
    namespace: cache
type: Opaque
stringData:
    users.acl: ENC[AES256_GCM,data:nUNwuBL36FQVo+T+fvK+Fi4j1Gm4qqFmApG1gZe69ebOVTAguaIi+pudkl9Xts7lB5mjyr4GYiQzycfu/2kAKGHa04oaw8zOlaqK/y7UDeHINUtycB7gkeuabadNO4dhrgD1To28CrcKjhP1Sw==,iv:is29eoqtQpa4RItg6Z2/4SItwWjAaaDXM7obQlKY434=,tag:0R1FS2o2Ie/KogY60hofJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TlRDbmVhUmhCdjBkZ09z
            NjNVWWVDZnZXWVkvbnFlbnBVRDRTV0ZjR0dFCmRIc3VZcjJ5RmVUK1pLQ2tvTVIr
            c1pnOEZBV1hmdTZlRU5RdjZlaHppZWcKLS0tIGdJdEpFcXU5ajRmSE1lU01KRW5I
            T3ZBRnBCT3RFNUFpbFFFVHI3bmU0TlkKzAPQojCT/jGtpUufm2WAH/VLPLMz6jXQ
            2vuJmNgFqoZR0pbWGw6vTrfLoBe+teeuuEU8s2khug/B8aITnbUylw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eyp26flc48tlgy32tmawjjvut92skkts9y3qycwtqpgqyunmu4zqjchqz6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T19:32:47Z"
    mac: ENC[AES256_GCM,data:iWbrAHfmxkQ5iOTUmY7W/WIyOOC1mwf9I9OrTyO+sRGXx7QR7T/m+1ge/lD5l4A5PAzh07Yi+JgPa7OScPmbCG3YFRCmkywWSrapzDwOjENXOULoKeXhZQdn6A/RUmNWSNTLALsGQUYvPmEflfusb7tJSs9jEDjn6yY14tYMv5g=,iv:q2wlnOpXagO6ejI5sDIvxhpY1tNbgRcf8dwX1HvQ7hw=,tag:L78MsP1zYJESvKKcONReeQ==,type:str]
    version: 3.13.3
