apiVersion: v1
kind: Secret
metadata:
    name: valkey-acl
    namespace: cache
type: Opaque
stringData:
    users.acl: ENC[AES256_GCM,data:lzfqn0KMJggmQCS9uY5uz2X5T5tLL26Fzgf4QCizHqoFzCDEEYdl0GuFOvUZDwWx2u7UDi36/5tI1Shao5qCqUu9gHzNL/6zOBtChGecghtdWzQQelXu587k4fQ3NIqpqLMgjh4lt5WUTnRWmfR/OMYMabYU9el0MMRq3ey8wx8DKSbXMSHrlezLngr95HLrtDi+FB/NZVgrkbkJphBf6goT2lzRQ3FmuJzVJ4Gsvo1Nk3aX9DDjsNDFbPMAtNDG/91nCNVsewDAeTSv43ucfxREoTEeP/IZ7RyTG5q7RUK6ZBTJajp0xdRgkgGOM72tK5kgH1DmEpmSqpEd8lBl7mf6CpAkfWvERLprDlN1DVhFKcLUV1U0m0Q3cevgJqa3xBkuvUIoJxG3T+zWi2XUlYzd2Dk3Ok5TDKKAivxa5rFJ+EPRcQu4Wr/65jkTq8YEHjP+4TPAigDH+7PlD+Dybq3FK02KDc71h2vsCzFhO9vJlOetSDsVdSrk+WvNV0OTKpM/pRQkVTtgmD3AoFL7JLtEQu98Cgj0g+h3wxtQ+DluvA==,iv:qteMp3AfCP6BFJCsaT6USkrLogfpB2PdCbWF7p8WCz8=,tag:pwuxgrrR6QLQMjzMpJ5Bmw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TlRDbmVhUmhCdjBkZ09z
            NjNVWWVDZnZXWVkvbnFlbnBVRDRTV0ZjR0dFCmRIc3VZcjJ5RmVUK1pLQ2tvTVIr
            c1pnOEZBV1hmdTZlRU5RdjZlaHppZWcKLS0tIGdJdEpFcXU5ajRmSE1lU01KRW5I
            T3ZBRnBCT3RFNUFpbFFFVHI3bmU0TlkKzAPQojCT/jGtpUufm2WAH/VLPLMz6jXQ
            2vuJmNgFqoZR0pbWGw6vTrfLoBe+teeuuEU8s2khug/B8aITnbUylw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eyp26flc48tlgy32tmawjjvut92skkts9y3qycwtqpgqyunmu4zqjchqz6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T06:18:26Z"
    mac: ENC[AES256_GCM,data:5MeFrEpxWTXMKjYa3JSnCJ2wrIc7+PDHAqWzqyPbvZhZdje1eoW/eyq1xxaVp3OAMO8a4/rgh8TsFscDAgKzKOX+cWkDjeNzsJiNfkB+6iAjlhmQJgItxmsgd9PEUPVxfOL7yvy0trVpJ5rG9dOAaBmGntKXkgZa2LELU2eS10Y=,iv:AHymOhd5efrZgfYv+xSCABXh2JsMVu+6mTL5imFTGcs=,tag:DihPnDxY3sju6Zece8XIwQ==,type:str]
    version: 3.13.3
