apiVersion: v1
kind: Secret
metadata:
    name: mariadb-shared-1
    namespace: databases
type: Opaque
stringData:
    root-password: ENC[AES256_GCM,data:HlsXX9kDcn74RfhWo0+QvmQNM5CY87IgFHcn98PVpJnVLO2qmL8eKl31DSMIha+0sBjtfchZfkaY+fnZ1MA8NA==,iv:e3/6ySvXC7riJONW4d3CX0QNXqLuaebyT4bga0CU0Io=,tag:uCgumBMS1EEB4sliryV8og==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0YlFOU2NLeFFwVGUvWHBn
            Q1hEb3R4b2pSQTBNaXV2VkdPZnEvOEFzdlFZCjkvY3RXdURuYkxSdE5reExRdFJJ
            bDlaVUVZMzV5RE1WZHBESjQ2M0VlZXcKLS0tIGIyM2t6RCtHeVdLanptZ2JiclJ4
            OGtCVXhVRmkzc3d4WDN4NTk5Nk91WHMK32XJjZxy5KJ1me9XZBGS0tVKOO/hRmXE
            4tV5354hrpjMNFGTcUEqQQojSgKUZfCfzwlcOxTeuT1YJXUl2RNfnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eyp26flc48tlgy32tmawjjvut92skkts9y3qycwtqpgqyunmu4zqjchqz6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T19:32:31Z"
    mac: ENC[AES256_GCM,data:vwCe4VrxBH2cONybBX+jGW71D9alSzm6kcq0iVoJ+9mEV2ZZWQKP3I/tgSCeuaUzy2JBJEqat0xgjZOi6YQ+okANOcj3oktMwQTCmjGUfhoxXN/+dcNC5MuQ0NF1SBpuVrP/0vyP5x/qSzRrmBPjIhbxKg3QTlPihJAFwMq0UPA=,iv:ulFXjNxwKPxEwMerXn9otZuvZ9UDnRoYvc0PQOgwjkc=,tag:WhnBevEXE8d+PDqcQbQJKQ==,type:str]
    version: 3.13.3
