apiVersion: v1
kind: Secret
metadata:
    name: juicefs-meta
    namespace: files
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:DdF3+6tdjAJRhCq20D3gg7+Bs99EZAYyMrQTMPte/Lt7JqKtfn1QaMw9Tt2kKBXm,iv:0Ddsri31hwJT6Gk5/1GP/46ML9Zltj6LIWd03qK5DMQ=,tag:Mb47PnRaMrEJ3eC2IAtS4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aTlKZU1SWWRCQ0trYUVP
            NlNodEFNQ1NFZUJIdmRYQTQ4b0RrZmc1VjBVCnlGcVlGZ0pHVmwxRW00dm9ZWVFw
            NHNuVldPVXVpMnBlYTRwSElZV2E2OEUKLS0tIG5rOFVWNlNQSks1SVFPZm90QUdZ
            bVM3cmNLU044Zi9CakJzVEEzQVNGeXMKaOFh4Y6HSF41B3abMpJTCHrQZqEKYiae
            93ZLo/KHJYSnO439P6zy71jXTY7K41TNUKShVRienH/bLOhprXatqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eyp26flc48tlgy32tmawjjvut92skkts9y3qycwtqpgqyunmu4zqjchqz6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T20:18:22Z"
    mac: ENC[AES256_GCM,data:YN8BwijLa1XfF1fW81nlQmxl01MiFrCgewNwhPr3yXwISJ/feU5eXXucK5G8j6n+wp5uaAv2CmYh/+wLyVLpnePa59Q+IF3f8QwjVPXSD2sXnciPdR5g21V+RPbdfpy17o6bHJ+6EUKoFc9gKy2Sd0c9pMGtYin0gQXsmhzNol0=,iv:sCw4/DSRTnUrfJkXBm1Ir/sNU/UDXNO7rJECbCs8n3E=,tag:bnyxc05iTDZ1f+akMDhKdw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: juicefs-secret
    namespace: files
    labels:
        juicefs.com/validate-secret: "true"
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:+LdVtDW7Gb2celRG,iv:1kNCGp923HxJeuiu/zThbnZYC80kbNq1vY5VuX3GGuY=,tag:s5+fe5ygggQSwz36DCQ0ZQ==,type:str]
    metaurl: ENC[AES256_GCM,data:6q/GNjk+dc5mPDImcwVL0sCYEfrQxz26JZEtJ0GFNuhpk0aKCcyodJOtXuVuT9cOLE7s/3tn6F+jpJJHU1r4JPg49tIa+RJimrFgZUvP4WaoE21YJOSRVQqGYEbFkvmiulWHuXoaAKLo6szXQjRi5tt+yI0=,iv:aqjJKni4nHpac2kdOtZqtHJzJnMsuylXorRZHS2ADhg=,tag:yGEzFYiyziFYgs00VySNeQ==,type:str]
    storage: ENC[AES256_GCM,data:BB4=,iv:YTmIQF7/guBm2pqQ3kjBs3elfTOiOzfitro8hIV3FJs=,tag:afsBI5FwUc+kEZmK7xOuag==,type:str]
    bucket: ENC[AES256_GCM,data:xvo0ULyMk+yPOBzi2suIN0ta6EphbYIGfmBhu9fiYICOP5kU71gQzy88aYEBuQsAV3Y=,iv:my8ge4cu126h2b+U5nh5oseiw0Cf1bnPKZz7OxUHsWA=,tag:F7RRpsy2lgwfE2z4olOurQ==,type:str]
    access-key: ENC[AES256_GCM,data:HpVBjCb3NvB8e6HSJv0C/rhrpqg=,iv:bbqx21XAnlsN5fYLmxIYxAXhF1dd/6k90VFaBqVdZWE=,tag:nlI4n1KDFkD+WSiBBJc/8A==,type:str]
    secret-key: ENC[AES256_GCM,data:M+s4xQoVWVpMXb/N+UxGRWzeFEJbFpNSksVL+D1lJDMhIkfg1h1Vkg==,iv:FbxRyDidtXEaCYz8xvhHkdZutVnRu8T0bASABdcQl9Q=,tag:oH5U+453GaHl7el7CH4YHw==,type:str]
    format-options: ENC[AES256_GCM,data:fM6qVqwZYDlj4km8,iv:8DFf1BCQrSJYPvA0egA8gkmnCzGXMduiTizlzufmG9M=,tag:SMUMbSnELwbLhYTKBVlMXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aTlKZU1SWWRCQ0trYUVP
            NlNodEFNQ1NFZUJIdmRYQTQ4b0RrZmc1VjBVCnlGcVlGZ0pHVmwxRW00dm9ZWVFw
            NHNuVldPVXVpMnBlYTRwSElZV2E2OEUKLS0tIG5rOFVWNlNQSks1SVFPZm90QUdZ
            bVM3cmNLU044Zi9CakJzVEEzQVNGeXMKaOFh4Y6HSF41B3abMpJTCHrQZqEKYiae
            93ZLo/KHJYSnO439P6zy71jXTY7K41TNUKShVRienH/bLOhprXatqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eyp26flc48tlgy32tmawjjvut92skkts9y3qycwtqpgqyunmu4zqjchqz6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T20:18:22Z"
    mac: ENC[AES256_GCM,data:YN8BwijLa1XfF1fW81nlQmxl01MiFrCgewNwhPr3yXwISJ/feU5eXXucK5G8j6n+wp5uaAv2CmYh/+wLyVLpnePa59Q+IF3f8QwjVPXSD2sXnciPdR5g21V+RPbdfpy17o6bHJ+6EUKoFc9gKy2Sd0c9pMGtYin0gQXsmhzNol0=,iv:sCw4/DSRTnUrfJkXBm1Ir/sNU/UDXNO7rJECbCs8n3E=,tag:bnyxc05iTDZ1f+akMDhKdw==,type:str]
    version: 3.13.3
