apiVersion: v1
kind: Secret
metadata:
    name: juicefs-meta
    namespace: files
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:dOWpZtNHoZJROKz2F2HUbEZwG2W8ePXMqf/5YM+wRCPafgsIIOZxamXDIvIcmqq0,iv:MrfJ+Tn7GsjTeiJVYV4sY60QC0NShqhh9tIkBo74mXo=,tag:G2bwH1crX5Tb0iWVEMgcUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVFBRWitWeVE1ZDlFU24v
            QnFPY24zYWdnTmdKNE5KZytXd3UvcENtSFhFCkRWRGE0UEZBQk1uWWwyQ2wyOFhK
            YkNTOGhvOC94NXE4Kzd1RUtjUEtmM2MKLS0tIGZ0elhWWlpzSXpnbFRxMTNWWWk1
            WlpQYjlqdDkwbUFjSFJOOE11RjFzZ2cKjaCgab07ZwBNfewKQzLeWrw5qUhbIPdh
            yk0NHQck+WV6LlgskY5r3odskwrkI0omVq6U/RJftAByl5yUAwxhPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eyp26flc48tlgy32tmawjjvut92skkts9y3qycwtqpgqyunmu4zqjchqz6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T08:45:59Z"
    mac: ENC[AES256_GCM,data:FA0pAp7+3veaSDVJJyR97tCt5Zq5qvb4uQtfPejG1qo+mLwo7R1N8odjyIb0KYUAUFWjWyj5P0C/K+Vy0fM6NR6ynqZVbUEMN0BxaEAgy2ViZZTlzunCQXXaCnTRWcx8IwaV9KnJ4LaIRj1xUHJ5jw/I5HmSOM1JErWUIiLFRNI=,iv:ZbGeyVTFDG6lM3p9vjcUYrYGohfdPH5joDWyIl7rQbI=,tag:rO9dl06bZLTtQ+1ljI+ClQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: juicefs-secret
    namespace: files
    labels:
        juicefs.com/validate-secret: "true"
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:U5q2SunQiLecdmBL,iv:1HhhhkpIc4FmKQ7tu0IKM027zFmlB7q3sRxLkbWkmkU=,tag:2a8xFjW9YR2PdTxJfux4Wg==,type:str]
    metaurl: ENC[AES256_GCM,data:ex4eGxLY8x4dnCUiPxnFWNTfarsSF3DPXaKsxWraXHTi2NlAQbsTyBeF1FT7dYInOpZgjsxVVCnZNwKYWrvWm9Hf6/cliIXbpm7ft08G8TC3IcYZ/HYfEPqQ6m9CneMkm8KOxFFhiI6xU/Pt3OnFusFAxQo=,iv:5zQGIWJfP59sm4HBp2flBHliKAe6xIlMucWDvklrLT4=,tag:EPSW+kFIxHqFYRlTRupOLQ==,type:str]
    storage: ENC[AES256_GCM,data:rDI=,iv:9igt3DGESrzxuzGGi1PKan8aEBLXs+JSej1P02isbBs=,tag:gsaF11gGiaI1D49Aq27RoQ==,type:str]
    bucket: ENC[AES256_GCM,data:v//ndpNR5S8NoV30zIPoCUq/1PCG7I3VqyqrbfclaQUVNF23jJFHtN7/8i9Au2dhra8TfJjSYnwz32yocSVT,iv:YlTNaqU9Id4XPwpuVdnNzU3lXUPdaiP23hgsJSGhBS8=,tag:2AY0cXlwNnhEWnVeMMcknw==,type:str]
    access-key: ENC[AES256_GCM,data:gvWSf1eR1QtqBd9k+kwpJFAAZQ4=,iv:KsM74YpGnCR/P3Bh2/wxI+uc1OoiXb4tT5pkd7Mjdg4=,tag:pXpDNDAZ/I+x6R7W3llsqA==,type:str]
    secret-key: ENC[AES256_GCM,data:ilDu0KJ1qACWCNG8/SIf0IPYZFZohhQoG0T8zjsIqSzDdMkh7MrUiQ==,iv:/AkpfiWpND7l3LpDK6vig3L4L5SkVzEi4XftyrpygrE=,tag:b+s3QZFsrF5Ey65e8BLXWw==,type:str]
    format-options: ENC[AES256_GCM,data:iw4yFCyXpjv1kXqU,iv:DcvadNuEi+JmDT2MblJzsq48JiOiWJjIPbdnZsUYPaA=,tag:oIR16EjEtnUURqobLRaHKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVFBRWitWeVE1ZDlFU24v
            QnFPY24zYWdnTmdKNE5KZytXd3UvcENtSFhFCkRWRGE0UEZBQk1uWWwyQ2wyOFhK
            YkNTOGhvOC94NXE4Kzd1RUtjUEtmM2MKLS0tIGZ0elhWWlpzSXpnbFRxMTNWWWk1
            WlpQYjlqdDkwbUFjSFJOOE11RjFzZ2cKjaCgab07ZwBNfewKQzLeWrw5qUhbIPdh
            yk0NHQck+WV6LlgskY5r3odskwrkI0omVq6U/RJftAByl5yUAwxhPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eyp26flc48tlgy32tmawjjvut92skkts9y3qycwtqpgqyunmu4zqjchqz6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T08:45:59Z"
    mac: ENC[AES256_GCM,data:FA0pAp7+3veaSDVJJyR97tCt5Zq5qvb4uQtfPejG1qo+mLwo7R1N8odjyIb0KYUAUFWjWyj5P0C/K+Vy0fM6NR6ynqZVbUEMN0BxaEAgy2ViZZTlzunCQXXaCnTRWcx8IwaV9KnJ4LaIRj1xUHJ5jw/I5HmSOM1JErWUIiLFRNI=,iv:ZbGeyVTFDG6lM3p9vjcUYrYGohfdPH5joDWyIl7rQbI=,tag:rO9dl06bZLTtQ+1ljI+ClQ==,type:str]
    version: 3.13.3
