apiVersion: v1
kind: Secret
metadata:
    name: hetzner-dns-token
    namespace: cert-manager
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:n2Ct/H9AZ516/abY/1WjS/nXQQzC8NQlaR4eYC/vLWmrlNvTaNXmm0//av+i3q2XS+R3O/fK+M9yCXLXAB/VcQ==,iv:nx8kngh499XaqGXqD30+XH+Fz8GNIyUeXub7a2D3A+A=,tag:+/9pyems/GQO55XsBt/4Zw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZHRBQkNsQXlXcUliWXhQ
            b1Z4RnZlc1I3ZkhNTGEzUjAzMExJQ0tRaUVvClpPdWlXMDlIQmNKdnJYeVJKN0tB
            Q0wwSVVUU2V1ZldXTmtLa0w3OXA1aWcKLS0tIDE2dHdicU5pSHZZMFpwRXRlbUdv
            SHlNM1g3QngxTUJ3MlJqQWROZHd6dzQKnVJ4o6OUSjFhvp5q4+5O69CdDusfBxek
            /sCed6a+1xWhm5CMdyKrVfHYfVdWEuHpF2XKpfGL0YD9qiqC5NSz7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eyp26flc48tlgy32tmawjjvut92skkts9y3qycwtqpgqyunmu4zqjchqz6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T20:53:58Z"
    mac: ENC[AES256_GCM,data:RG3TPpxB095+51apK3fdjtTnr4vVuHE7CtaNhCe+vWSRq4zf8ZqFJk9aBDtKEZu1yiop4XWKg6jCNzwsZAj7nML01tolCgq1kjeSWh06Bo9skM+sQdjITXTpDrAR3In5UkNm5xhU19fsy98Y7kSrL415lEMR0J4aR7mEzH8V964=,iv:dW7ZJsQB3WU9P0OoEi+3OGvZnFy/ZrK6v5FFzoKCo5Q=,tag:/v7HpoTub9ZBWGE1XoS0uw==,type:str]
    version: 3.13.3
